# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get.quant.err <- function(dist_cross) {
    .Call('_SomQualityCheck_GetQuantizationError', PACKAGE = 'SomQualityCheck', dist_cross)
}

get.top.err <- function(dist_cross, xdim) {
    .Call('_SomQualityCheck_GetTopographicError', PACKAGE = 'SomQualityCheck', dist_cross, xdim)
}

get.top.func <- function(dist_cross, xdim) {
    .Call('_SomQualityCheck_GetTopographicFunction', PACKAGE = 'SomQualityCheck', dist_cross, xdim)
}

get.hood.pres <- function(dist_data, dist_proj, k) {
    .Call('_SomQualityCheck_GetNeighborhoodPreservation', PACKAGE = 'SomQualityCheck', dist_data, dist_proj, k)
}

get.v.measure <- function(labels, clusters, beta = 1.0) {
    .Call('_SomQualityCheck_GetVMeasure', PACKAGE = 'SomQualityCheck', labels, clusters, beta)
}

